# Generated by Django 6.0.4 on 2026-04-25 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimedIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_id', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('repo_name', models.CharField(max_length=255)),
                ('issue_url', models.URLField()),
                ('status', models.CharField(choices=[('Focused', 'Focused'), ('Paused', 'Paused'), ('Submitted', 'Submitted'), ('Done', 'Done')], default='Focused', max_length=20)),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('time_spent_secs', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
