# Generated by Django 6.0.4 on 2026-04-25 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimedissue',
            name='notes',
            field=models.TextField(blank=True, max_length=5000),
        ),
    ]
